import type { ServiceContent } from "@/components/service-page";

const alternates = {
  tr: "/yapay-zeka",
  en: "/en/ai-solutions",
  sq: "/sq/inteligjence-artificiale",
} as const;

export const aiTR: ServiceContent = {
  locale: "tr",
  slug: alternates.tr,
  alternates,
  meta: {
    title: "Yapay Zekâ Çözümleri ve AI Otomasyon — İşletmeler İçin",
    description:
      "İşletmeler için yapay zekâ çözümleri: AI ajanları, sohbet asistanları, iş süreçleri otomasyonu ve mevcut yazılımlara AI entegrasyonu. İzmir merkezli, Türkiye geneli ve yurt dışı.",
    keywords: [
      "yapay zeka çözümleri",
      "AI otomasyon",
      "AI ajan geliştirme",
      "yapay zeka entegrasyonu",
      "chatbot geliştirme",
      "iş süreçleri otomasyonu",
      "yapay zeka yazılım İzmir",
    ],
  },
  eyebrow: "Yapay Zekâ",
  h1: ["Yapay zekâyı", "işinizin içine kuruyoruz."],
  lead: "WoodstoneStudio, işletmeler için yapay zekâ çözümleri geliştiren bir dijital teknoloji stüdyosudur. Sohbet asistanları, belirli görevleri yürüten AI ajanları ve tekrar eden işleri ortadan kaldıran otomasyonlar kuruyor; bunları mevcut yazılımlarınıza ve süreçlerinize entegre ediyoruz. Kendi ürünlerimizde AI'ı üretimde kullanıyoruz.",
  ctaPrimary: "Ücretsiz Ön Görüşme",
  ctaSecondary: "Çalışmaları Görün",
  scopeTitle: ["Neler", "yapıyoruz?"],
  scopeLead: "Yapay zekâ bir gösteri değil, bir araçtır. Somut bir iş problemini çözdüğünde değerlidir — biz oradan başlıyoruz.",
  scope: [
    { title: "AI sohbet asistanları", desc: "Müşteri sorularını yanıtlayan, siparişe yönlendiren ya da iç ekibe destek olan, kendi verinizle eğitilmiş asistanlar." },
    { title: "AI ajanları", desc: "Belirli bir görevi baştan sona yürüten ajanlar: veri toplama, rapor hazırlama, e-posta sınıflandırma, içerik üretimi." },
    { title: "İş süreçleri otomasyonu", desc: "Tekrar eden manuel işleri otomatikleştiriyoruz; bir adım bitince sıradaki kendiliğinden başlar." },
    { title: "Mevcut yazılıma AI entegrasyonu", desc: "Kullandığınız uygulamaya ya da web sitesine yapay zekâ özellikleri ekliyoruz — sıfırdan yazmadan." },
    { title: "Görsel ve belge analizi", desc: "Fotoğraf, belge ve PDF'lerden bilgi çıkaran, sınıflandıran ve özetleyen çözümler." },
    { title: "AI destekli ürünler", desc: "Yapay zekâyı merkezine alan yeni web ve mobil ürünleri fikirden yayına geliştiriyoruz." },
  ],
  processTitle: ["Nasıl", "çalışıyoruz?"],
  process: [
    { step: "01", title: "Problem tanımı", desc: "Hangi işin, ne kadar zaman ya da maliyet yarattığını netleştiriyoruz. Ücretsiz." },
    { step: "02", title: "Pilot", desc: "Küçük bir kapsamda çalışan bir prototip kurup gerçek veriyle test ediyoruz." },
    { step: "03", title: "Entegrasyon", desc: "Çözümü mevcut sistemlerinize ve ekibinizin akışına bağlıyoruz." },
    { step: "04", title: "Yaygınlaştırma", desc: "Sonuçları ölçüyor, kapsamı genişletiyor ve bakımını sürdürüyoruz." },
  ],
  faqTitle: ["Sık sorulan", "sorular."],
  faq: [
    { q: "Yapay zekâ benim işime gerçekten uyar mı?", a: "Tekrar eden, kural tabanlı ya da metin/görsel işleyen her iş için büyük ihtimalle evet. Ön görüşmede somut bir kullanım alanı belirliyoruz; uymuyorsa bunu açıkça söylüyoruz." },
    { q: "Hangi AI modellerini kullanıyorsunuz?", a: "İhtiyaca göre OpenAI, Anthropic ve Google modellerini kullanıyoruz; gerektiğinde kendi verinizle özelleştiriyoruz." },
    { q: "Verilerim güvende olur mu?", a: "Evet. Veri işleme kurallarını baştan belirliyor, hassas verinin nasıl saklanıp işleneceğini sizinle netleştiriyoruz." },
    { q: "Mevcut yazılımıma eklenebilir mi?", a: "Evet. Çoğu durumda sıfırdan yazmaya gerek kalmadan, kullandığınız sisteme AI özellikleri entegre ediyoruz." },
    { q: "Bir AI projesi ne kadar sürer?", a: "Küçük bir pilot 2–4 hafta; tam entegrasyon kapsama göre 1–3 ay. Ön görüşmede net bir takvim veriyoruz." },
    { q: "Maliyeti nasıl belirleniyor?", a: "Kapsama ve entegrasyon derinliğine göre yazılı teklif hazırlıyoruz; model kullanım maliyetlerini de şeffaf şekilde paylaşıyoruz." },
  ],
  closingTitle: ["Yapay zekâ fikriniz için", "konuşalım."],
  closingLead: "Hangi işi hızlandırmak istediğinizi anlatın; ücretsiz ön görüşmede somut bir kullanım alanı ve yol haritası çıkaralım.",
  closingCta: "Bize Ulaşın",
  backLabel: "Ana sayfa",
  serviceType: "Yapay zekâ çözümleri ve AI otomasyon",
  areaServed: "Türkiye ve yurt dışı",
};

export const aiEN: ServiceContent = {
  locale: "en",
  slug: alternates.en,
  alternates,
  meta: {
    title: "AI Solutions & Automation for Businesses",
    description:
      "AI solutions for businesses: AI agents, chat assistants, business process automation and AI integration into existing software. Studio based in İzmir, Turkey, working worldwide.",
    keywords: [
      "AI solutions for business",
      "AI automation",
      "AI agent development",
      "AI integration",
      "chatbot development",
      "business process automation",
      "AI development studio",
    ],
  },
  eyebrow: "AI Solutions",
  h1: ["We build AI", "into your business."],
  lead: "WoodstoneStudio is a digital technology studio building AI solutions for businesses. Chat assistants, task-running AI agents and automations that remove repetitive work — integrated into your existing software and processes. We run AI in production in our own products.",
  ctaPrimary: "Free Consultation",
  ctaSecondary: "See Our Work",
  scopeTitle: ["What we", "do."],
  scopeLead: "AI is a tool, not a show. It's valuable when it solves a concrete business problem — that's where we start.",
  scope: [
    { title: "AI chat assistants", desc: "Assistants trained on your own data that answer customer questions, guide orders or support your internal team." },
    { title: "AI agents", desc: "Agents that run a specific task end to end: data collection, report generation, email triage, content production." },
    { title: "Business process automation", desc: "We automate repetitive manual work; when one step finishes, the next starts on its own." },
    { title: "AI integration into existing software", desc: "We add AI features to the app or website you already use — without rewriting from scratch." },
    { title: "Image & document analysis", desc: "Solutions that extract, classify and summarise information from photos, documents and PDFs." },
    { title: "AI-powered products", desc: "New web and mobile products with AI at the core, built from idea to launch." },
  ],
  processTitle: ["How we", "work."],
  process: [
    { step: "01", title: "Problem definition", desc: "We pin down which task costs you time or money. Free." },
    { step: "02", title: "Pilot", desc: "A working prototype on a small scope, tested with real data." },
    { step: "03", title: "Integration", desc: "We connect the solution to your existing systems and your team's workflow." },
    { step: "04", title: "Roll-out", desc: "We measure results, expand the scope and keep it maintained." },
  ],
  faqTitle: ["Frequently asked", "questions."],
  faq: [
    { q: "Does AI really fit my business?", a: "For any repetitive, rule-based or text/image-heavy task, most likely yes. At the consultation we identify a concrete use case — and if it doesn't fit, we say so." },
    { q: "Which AI models do you use?", a: "Depending on the need, models from OpenAI, Anthropic and Google, customised with your own data where required." },
    { q: "Is my data safe?", a: "Yes. We define data-handling rules from the start and agree with you how sensitive data is stored and processed." },
    { q: "Can it be added to my existing software?", a: "Yes. In most cases we integrate AI features into the system you already use, without a rewrite." },
    { q: "How long does an AI project take?", a: "A small pilot 2–4 weeks; full integration 1–3 months depending on scope. We give a clear timeline at the consultation." },
    { q: "How is it priced?", a: "A written quote based on scope and integration depth; we also share model usage costs transparently." },
  ],
  closingTitle: ["Let's talk about", "your AI idea."],
  closingLead: "Tell us which task you want to speed up; in a free consultation we'll map a concrete use case and a roadmap.",
  closingCta: "Get in Touch",
  backLabel: "Home",
  serviceType: "AI solutions and automation",
  areaServed: "Worldwide",
};

export const aiSQ: ServiceContent = {
  locale: "sq",
  slug: alternates.sq,
  alternates,
  meta: {
    title: "Zgjidhje me Inteligjencë Artificiale dhe Automatizim për Biznese",
    description:
      "Zgjidhje me inteligjencë artificiale për biznese në Shqipëri dhe Kosovë: agjentë AI, asistentë bisede, automatizim i proceseve të biznesit dhe integrim i AI në softuerin ekzistues.",
    keywords: [
      "inteligjencë artificiale për biznes",
      "automatizim me AI",
      "zhvillim agjentësh AI",
      "integrim inteligjence artificiale",
      "chatbot Shqipëri",
      "automatizim i proceseve",
      "zgjidhje AI Shqipëri",
    ],
  },
  eyebrow: "Inteligjencë Artificiale",
  h1: ["Inteligjencën artificiale", "e ndërtojmë brenda biznesit tuaj."],
  lead: "WoodstoneStudio është një studio teknologjie dixhitale që ndërton zgjidhje me inteligjencë artificiale për biznese në Shqipëri, Kosovë dhe më gjerë. Asistentë bisede, agjentë AI që kryejnë detyra dhe automatizime që heqin punën e përsëritur — të integruara në softuerin dhe proceset tuaja ekzistuese. AI e përdorim në prodhim në produktet tona.",
  ctaPrimary: "Konsultë Falas",
  ctaSecondary: "Shihni Punët Tona",
  scopeTitle: ["Çfarë", "bëjmë?"],
  scopeLead: "Inteligjenca artificiale është një mjet, jo një shfaqje. Ka vlerë kur zgjidh një problem konkret biznesi — nga aty fillojmë.",
  scope: [
    { title: "Asistentë bisede me AI", desc: "Asistentë të trajnuar me të dhënat tuaja që u përgjigjen pyetjeve të klientëve, drejtojnë porositë ose mbështesin ekipin e brendshëm." },
    { title: "Agjentë AI", desc: "Agjentë që kryejnë një detyrë nga fillimi në fund: mbledhje të dhënash, përgatitje raportesh, klasifikim emailesh, prodhim përmbajtjeje." },
    { title: "Automatizim i proceseve të biznesit", desc: "Automatizojmë punët manuale të përsëritura; kur mbaron një hap, tjetri fillon vetë." },
    { title: "Integrim i AI në softuerin ekzistues", desc: "Shtojmë veçori AI në aplikacionin ose faqen që përdorni tashmë — pa e rishkruar nga zero." },
    { title: "Analizë imazhesh dhe dokumentesh", desc: "Zgjidhje që nxjerrin, klasifikojnë dhe përmbledhin informacion nga foto, dokumente dhe PDF." },
    { title: "Produkte me AI në qendër", desc: "Produkte të reja web dhe mobile me inteligjencën artificiale në thelb, nga ideja në publikim." },
  ],
  processTitle: ["Si", "punojmë?"],
  process: [
    { step: "01", title: "Përcaktimi i problemit", desc: "Qartësojmë cila punë ju kushton kohë ose para. Falas." },
    { step: "02", title: "Pilot", desc: "Një prototip funksional në fushëveprim të vogël, i testuar me të dhëna reale." },
    { step: "03", title: "Integrim", desc: "E lidhim zgjidhjen me sistemet tuaja ekzistuese dhe rrjedhën e punës së ekipit." },
    { step: "04", title: "Shtrirje", desc: "Masim rezultatet, zgjerojmë fushëveprimin dhe e mbajmë në mirëmbajtje." },
  ],
  faqTitle: ["Pyetje të", "bëra shpesh."],
  faq: [
    { q: "A i përshtatet vërtet inteligjenca artificiale biznesit tim?", a: "Për çdo detyrë të përsëritur, të bazuar në rregulla ose me shumë tekst/imazhe, me shumë gjasa po. Në konsultë përcaktojmë një rast konkret përdorimi — dhe nëse nuk përshtatet, e themi hapur." },
    { q: "Cilat modele AI përdorni?", a: "Sipas nevojës, modele nga OpenAI, Anthropic dhe Google, të personalizuara me të dhënat tuaja kur kërkohet." },
    { q: "A janë të dhënat e mia të sigurta?", a: "Po. Rregullat e trajtimit të të dhënave i përcaktojmë që në fillim dhe bihet dakord me ju se si ruhen dhe përpunohen të dhënat e ndjeshme." },
    { q: "A mund të shtohet në softuerin tim ekzistues?", a: "Po. Në shumicën e rasteve integrojmë veçori AI në sistemin që përdorni tashmë, pa rishkrim." },
    { q: "Sa kohë zgjat një projekt AI?", a: "Një pilot i vogël 2–4 javë; integrimi i plotë 1–3 muaj sipas fushëveprimit. Në konsultë japim një afat të qartë." },
    { q: "Si përcaktohet çmimi?", a: "Ofertë me shkrim bazuar në fushëveprim dhe thellësinë e integrimit; kostot e përdorimit të modeleve i ndajmë me transparencë." },
  ],
  closingTitle: ["Le të flasim për", "idenë tuaj me AI."],
  closingLead: "Na tregoni cilën punë doni ta përshpejtoni; në një konsultë falas hartojmë një rast konkret përdorimi dhe një udhërrëfyes.",
  closingCta: "Na Kontaktoni",
  backLabel: "Faqja kryesore",
  serviceType: "Zgjidhje me inteligjencë artificiale dhe automatizim",
  areaServed: "Shqipëri, Kosovë",
};
