import type { ServiceContent } from "@/components/service-page";

const alternates = {
  tr: "/mobil-uygulama",
  en: "/en/mobile-apps",
  sq: "/sq/aplikacione-mobile",
} as const;

export const mobileTR: ServiceContent = {
  locale: "tr",
  slug: alternates.tr,
  alternates,
  meta: {
    title: "İzmir Mobil Uygulama Geliştirme — iOS ve Android",
    description:
      "İzmir merkezli mobil uygulama geliştirme stüdyosu. Flutter ile tek kod tabanından iOS ve Android uygulamalar; App Store ve Google Play yayını dahil. Ücretsiz ön görüşme.",
    keywords: [
      "İzmir mobil uygulama",
      "mobil uygulama geliştirme İzmir",
      "mobil uygulama yaptırmak",
      "Flutter uygulama geliştirme",
      "iOS Android uygulama",
      "App Store Google Play yayınlama",
      "uygulama geliştirme firması",
    ],
  },
  eyebrow: "Mobil Uygulama · İzmir",
  h1: ["Mobil uygulama:", "fikirden mağazaya."],
  lead: "WoodstoneStudio, İzmir merkezli bir dijital teknoloji stüdyosudur. Flutter ile tek kod tabanından iOS ve Android uygulamalar geliştiriyor; tasarımdan App Store ve Google Play yayınına kadar tüm süreci üstleniyoruz. Kendi uygulamalarımız mağazalarda yayında — süreci yaşayarak biliyoruz.",
  ctaPrimary: "Ücretsiz Ön Görüşme",
  ctaSecondary: "Çalışmaları Görün",
  scopeTitle: ["Neler", "yapıyoruz?"],
  scopeLead: "Bir uygulama sadece kodlanmaz; mağaza onayından geçer, kullanıcıya ulaşır ve yaşatılır. Hepsini tek elden yürütüyoruz.",
  scope: [
    { title: "iOS ve Android uygulama", desc: "Flutter ile tek kod tabanından her iki platforma yayın; tek ekip, tek bütçe, iki mağaza." },
    { title: "MVP ve ilk sürüm", desc: "Fikrinizi en kısa sürede test edilebilir bir ilk sürüme dönüştürüyoruz; geri bildirimle büyütüyoruz." },
    { title: "Yapay zekâ destekli uygulamalar", desc: "Sohbet, görsel tanıma, içerik üretimi gibi AI özelliklerini uygulamanıza entegre ediyoruz." },
    { title: "Backend ve altyapı", desc: "Kullanıcı yönetimi, veritabanı, bildirimler ve ödeme altyapısı (abonelik, uygulama içi satın alma) kuruyoruz." },
    { title: "Mağaza yayını", desc: "App Store ve Google Play başvurusu, inceleme süreci, mağaza metinleri ve görselleri — onaydan geçene kadar yanınızdayız." },
    { title: "Güncelleme ve bakım", desc: "Yayından sonra sürüm güncellemeleri, hata düzeltmeleri ve yeni özellikler için çalışmaya devam ediyoruz." },
  ],
  processTitle: ["Nasıl", "çalışıyoruz?"],
  process: [
    { step: "01", title: "Ön görüşme", desc: "Fikrinizi, hedef kullanıcınızı ve öncelikli özellikleri netleştiriyoruz. Ücretsiz." },
    { step: "02", title: "Tasarım", desc: "Ekran akışlarını ve arayüzü tasarlıyor; onayınızla geliştirmeye geçiyoruz." },
    { step: "03", title: "Geliştirme", desc: "Flutter ile iOS ve Android'i birlikte geliştiriyor, test sürümlerini sizinle paylaşıyoruz." },
    { step: "04", title: "Yayın ve destek", desc: "Mağaza başvurularını yapıp onay sürecini yönetiyoruz; sonrasında bakım sürüyor." },
  ],
  faqTitle: ["Sık sorulan", "sorular."],
  faq: [
    { q: "Mobil uygulama yaptırmak ne kadar sürer?", a: "Basit bir MVP 4–6 hafta, orta ölçekli bir uygulama 2–3 ay sürer. Kapsama göre ön görüşmede net bir takvim veriyoruz." },
    { q: "Uygulama hem iOS hem Android'de çalışır mı?", a: "Evet. Flutter ile tek kod tabanından her iki platforma yayın yapıyoruz; ayrı ayrı geliştirme maliyetine göre çok daha ekonomiktir." },
    { q: "App Store ve Google Play yayınını siz mi yapıyorsunuz?", a: "Evet. Başvuru, mağaza metinleri, görseller ve inceleme sürecini biz yönetiyoruz. Kendi uygulamalarımızı yayınladığımız için süreci iyi biliyoruz." },
    { q: "Uygulamaya yapay zekâ eklenebilir mi?", a: "Evet. Sohbet asistanı, görsel analiz, kişiselleştirilmiş içerik gibi AI özelliklerini uygulamalara entegre ediyoruz." },
    { q: "Sadece fikrim var, yeterli mi?", a: "Evet. Birçok projeye yalnızca fikirle başlıyoruz; kapsamı birlikte netleştirip bir MVP ile hayata geçiriyoruz." },
    { q: "Yayından sonra destek veriyor musunuz?", a: "Evet. İşletim sistemi güncellemeleri, hata düzeltmeleri ve yeni özellikler için bakım anlaşmasıyla çalışmaya devam ediyoruz." },
  ],
  closingTitle: ["Uygulamanız için", "konuşalım."],
  closingLead: "Fikrinizi anlatın; ücretsiz ön görüşmede kapsamı, süreyi ve maliyeti birlikte netleştirelim.",
  closingCta: "Bize Ulaşın",
  backLabel: "Ana sayfa",
  serviceType: "Mobil uygulama geliştirme (iOS ve Android)",
  areaServed: "İzmir, Türkiye",
};

export const mobileEN: ServiceContent = {
  locale: "en",
  slug: alternates.en,
  alternates,
  meta: {
    title: "Mobile App Development — iOS & Android with Flutter",
    description:
      "Mobile app development studio based in İzmir, Turkey. iOS and Android apps from a single Flutter codebase, App Store and Google Play publishing included. Free consultation.",
    keywords: [
      "mobile app development",
      "Flutter app development",
      "iOS Android app development",
      "mobile app studio Turkey",
      "MVP app development",
      "App Store Google Play publishing",
      "AI mobile app",
    ],
  },
  eyebrow: "Mobile Apps",
  h1: ["Mobile apps,", "from idea to the store."],
  lead: "WoodstoneStudio is a digital technology studio based in İzmir, Turkey. We build iOS and Android apps from a single Flutter codebase and handle everything from design to App Store and Google Play release. Our own apps are live in both stores — we know the process first-hand.",
  ctaPrimary: "Free Consultation",
  ctaSecondary: "See Our Work",
  scopeTitle: ["What we", "do."],
  scopeLead: "An app is not just written; it passes store review, reaches users and stays alive. We run the whole journey under one roof.",
  scope: [
    { title: "iOS & Android apps", desc: "One Flutter codebase, both platforms — one team, one budget, two stores." },
    { title: "MVP & first release", desc: "We turn your idea into a testable first version fast, then grow it with real user feedback." },
    { title: "AI-powered apps", desc: "Chat assistants, image recognition, content generation — we integrate AI features into your app." },
    { title: "Backend & infrastructure", desc: "User accounts, database, push notifications and payments (subscriptions, in-app purchases)." },
    { title: "Store publishing", desc: "App Store and Google Play submission, review process, store listings and screenshots — with you until approval." },
    { title: "Updates & maintenance", desc: "Version updates, bug fixes and new features after launch." },
  ],
  processTitle: ["How we", "work."],
  process: [
    { step: "01", title: "Consultation", desc: "We clarify your idea, target users and priority features. Free." },
    { step: "02", title: "Design", desc: "Screen flows and interface, developed further with your approval." },
    { step: "03", title: "Development", desc: "iOS and Android built together in Flutter, with test builds shared along the way." },
    { step: "04", title: "Launch & support", desc: "Store submissions and review handled; maintenance continues after release." },
  ],
  faqTitle: ["Frequently asked", "questions."],
  faq: [
    { q: "How long does a mobile app take?", a: "A simple MVP takes 4–6 weeks, a mid-sized app 2–3 months. We give a clear timeline at the consultation." },
    { q: "Will the app run on both iOS and Android?", a: "Yes. We build both platforms from a single Flutter codebase, which is far more economical than developing them separately." },
    { q: "Do you handle App Store and Google Play publishing?", a: "Yes. We manage submission, store listings, screenshots and the review process. We publish our own apps, so we know it well." },
    { q: "Can AI be added to the app?", a: "Yes. We integrate features like chat assistants, image analysis and personalised content." },
    { q: "I only have an idea — is that enough?", a: "Yes. Many projects start with just an idea; we define the scope together and bring it to life with an MVP." },
    { q: "Do you provide support after launch?", a: "Yes. We continue with a maintenance agreement for OS updates, bug fixes and new features." },
  ],
  closingTitle: ["Let's talk about", "your app."],
  closingLead: "Tell us your idea; in a free consultation we'll clarify scope, timeline and cost together.",
  closingCta: "Get in Touch",
  backLabel: "Home",
  serviceType: "Mobile app development (iOS and Android)",
  areaServed: "Worldwide",
};

export const mobileSQ: ServiceContent = {
  locale: "sq",
  slug: alternates.sq,
  alternates,
  meta: {
    title: "Zhvillim Aplikacionesh Mobile në Shqipëri — iOS dhe Android",
    description:
      "Studio zhvillimi aplikacionesh mobile që punon me klientë në Shqipëri dhe Kosovë. Aplikacione iOS dhe Android nga një kod i vetëm Flutter, publikimi në App Store dhe Google Play i përfshirë. Konsultë falas.",
    keywords: [
      "zhvillim aplikacionesh mobile",
      "aplikacion mobile Shqipëri",
      "aplikacion Android iOS Tiranë",
      "zhvillim aplikacioni Flutter",
      "krijim aplikacioni mobil",
      "publikim App Store Google Play",
      "aplikacion me inteligjencë artificiale",
    ],
  },
  eyebrow: "Aplikacione Mobile",
  h1: ["Aplikacione mobile,", "nga ideja në dyqan."],
  lead: "WoodstoneStudio është një studio teknologjie dixhitale që punon me klientë në Shqipëri, Kosovë dhe rajon. Ndërtojmë aplikacione iOS dhe Android nga një kod i vetëm Flutter dhe kujdesemi për gjithçka, nga dizajni deri te publikimi në App Store dhe Google Play. Aplikacionet tona janë live në të dyja dyqanet — procesin e njohim nga përvoja.",
  ctaPrimary: "Konsultë Falas",
  ctaSecondary: "Shihni Punët Tona",
  scopeTitle: ["Çfarë", "bëjmë?"],
  scopeLead: "Një aplikacion nuk vetëm shkruhet; ai kalon rishikimin e dyqanit, arrin te përdoruesit dhe mbahet gjallë. Të gjithë rrugëtimin e drejtojmë nën një çati.",
  scope: [
    { title: "Aplikacione iOS dhe Android", desc: "Një kod i vetëm Flutter, të dyja platformat — një ekip, një buxhet, dy dyqane." },
    { title: "MVP dhe versioni i parë", desc: "Idenë tuaj e kthejmë shpejt në një version të parë të testueshëm dhe e rrisim me reagimet e përdoruesve." },
    { title: "Aplikacione me inteligjencë artificiale", desc: "Asistentë bisede, njohje imazhesh, gjenerim përmbajtjeje — i integrojmë veçoritë e AI në aplikacionin tuaj." },
    { title: "Backend dhe infrastrukturë", desc: "Llogari përdoruesish, bazë të dhënash, njoftime push dhe pagesa (abonime, blerje brenda aplikacionit)." },
    { title: "Publikim në dyqane", desc: "Dorëzimi në App Store dhe Google Play, procesi i rishikimit, tekstet dhe pamjet e dyqanit — me ju deri në miratim." },
    { title: "Përditësime dhe mirëmbajtje", desc: "Përditësime versionesh, rregullime gabimesh dhe veçori të reja pas publikimit." },
  ],
  processTitle: ["Si", "punojmë?"],
  process: [
    { step: "01", title: "Konsultë", desc: "Qartësojmë idenë, përdoruesit e synuar dhe veçoritë me përparësi. Falas." },
    { step: "02", title: "Dizajn", desc: "Rrjedhat e ekraneve dhe ndërfaqja, të zhvilluara më tej me miratimin tuaj." },
    { step: "03", title: "Zhvillim", desc: "iOS dhe Android të ndërtuara së bashku në Flutter, me versione testimi që i ndajmë gjatë rrugës." },
    { step: "04", title: "Publikim dhe mbështetje", desc: "Kujdesemi për dorëzimin dhe rishikimin në dyqane; mirëmbajtja vazhdon pas publikimit." },
  ],
  faqTitle: ["Pyetje të", "bëra shpesh."],
  faq: [
    { q: "Sa kohë zgjat ndërtimi i një aplikacioni mobil?", a: "Një MVP i thjeshtë zgjat 4–6 javë, një aplikacion i mesëm 2–3 muaj. Në konsultë japim një afat të qartë." },
    { q: "A do të funksionojë aplikacioni në iOS dhe Android?", a: "Po. Të dyja platformat i ndërtojmë nga një kod i vetëm Flutter, që është shumë më ekonomik se zhvillimi i veçantë." },
    { q: "A kujdeseni ju për publikimin në App Store dhe Google Play?", a: "Po. Menaxhojmë dorëzimin, tekstet e dyqanit, pamjet dhe procesin e rishikimit. Publikojmë aplikacionet tona, ndaj e njohim mirë." },
    { q: "A mund t'i shtohet inteligjencë artificiale aplikacionit?", a: "Po. Integrojmë veçori si asistentë bisede, analizë imazhesh dhe përmbajtje të personalizuar." },
    { q: "Kam vetëm një ide — a mjafton?", a: "Po. Shumë projekte nisin vetëm me një ide; fushëveprimin e përcaktojmë së bashku dhe e sjellim në jetë me një MVP." },
    { q: "A ofroni mbështetje pas publikimit?", a: "Po. Vazhdojmë me një marrëveshje mirëmbajtjeje për përditësimet e sistemit, rregullimet dhe veçoritë e reja." },
  ],
  closingTitle: ["Le të flasim për", "aplikacionin tuaj."],
  closingLead: "Na tregoni idenë tuaj; në një konsultë falas qartësojmë së bashku fushëveprimin, afatin dhe koston.",
  closingCta: "Na Kontaktoni",
  backLabel: "Faqja kryesore",
  serviceType: "Zhvillim aplikacionesh mobile (iOS dhe Android)",
  areaServed: "Shqipëri, Kosovë",
};
