import type { ServiceContent } from "@/components/service-page";

const alternates = {
  tr: "/saas-gelistirme",
  en: "/en/saas-development",
  sq: "/sq/zhvillim-saas",
} as const;

export const saasTR: ServiceContent = {
  locale: "tr",
  slug: alternates.tr,
  alternates,
  meta: {
    title: "SaaS ve MVP Geliştirme — Fikirden Ürüne",
    description:
      "SaaS ürünü ve MVP geliştirme stüdyosu. Abonelik tabanlı web uygulamaları, kullanıcı yönetimi, ödeme altyapısı ve ölçeklenebilir mimari; fikrinizi hızla test edilebilir bir ürüne dönüştürüyoruz.",
    keywords: [
      "SaaS geliştirme",
      "MVP geliştirme",
      "SaaS yazılım geliştirme",
      "startup MVP yaptırmak",
      "web uygulaması geliştirme",
      "abonelik sistemi yazılım",
      "Next.js SaaS",
    ],
  },
  eyebrow: "SaaS ve MVP",
  h1: ["SaaS fikrinizi", "gerçek bir ürüne çevirin."],
  lead: "Woodstone Studio, SaaS ürünlerini fikirden yayına kadar geliştiren bir dijital teknoloji stüdyosudur. Önce çekirdek özellikleri içeren bir MVP kuruyor, gerçek kullanıcı geri bildirimiyle büyütüyoruz. Kendi SaaS ürünlerimizi de geliştiriyoruz — ürün düşüncesini içeriden biliyoruz.",
  ctaPrimary: "Ücretsiz Ön Değerlendirme",
  ctaSecondary: "Çalışmaları Görün",
  scopeTitle: ["Neler", "yapıyoruz?"],
  scopeLead: "Bir SaaS ürünü sadece arayüz değildir; abonelik, kullanıcı, ödeme ve ölçeklenebilirlik demektir. Hepsini birlikte kuruyoruz.",
  scope: [
    { title: "MVP geliştirme", desc: "Fikrinizin en kritik özelliklerini içeren, haftalar içinde yayına alınabilecek ilk sürüm; pazarı erken test etmek için." },
    { title: "Abonelik tabanlı uygulamalar", desc: "Plan yapısı, deneme süresi, abonelik yönetimi ve faturalandırma; Stripe gibi altyapılarla ödeme entegrasyonu." },
    { title: "Kullanıcı ve yetki yönetimi", desc: "Kayıt, giriş, ekip/organizasyon yapısı, roller ve izinler — çok kullanıcılı ürünler için sağlam temel." },
    { title: "Kontrol paneli ve raporlama", desc: "Kullanıcıların işini yönettiği paneller, veri tabloları, grafikler ve dışa aktarma." },
    { title: "API ve entegrasyonlar", desc: "Üçüncü taraf servislerle (ödeme, e-posta, CRM, AI) entegrasyon ve kendi API'nizin tasarımı." },
    { title: "Ölçeklenebilir mimari", desc: "Next.js, React ve modern bulut altyapısıyla büyüdükçe sizi yavaşlatmayan bir teknik temel." },
  ],
  processTitle: ["Nasıl", "çalışıyoruz?"],
  process: [
    { step: "01", title: "Ön değerlendirme", desc: "Fikri, hedef kullanıcıyı ve gelir modelini netleştiriyoruz. Ücretsiz." },
    { step: "02", title: "MVP kapsamı", desc: "İlk sürüme girecek çekirdek özellikleri belirleyip yol haritası çıkarıyoruz." },
    { step: "03", title: "Geliştirme", desc: "Haftalık teslimatlarla ürünü kuruyor, her adımda sizinle test ediyoruz." },
    { step: "04", title: "Yayın ve büyütme", desc: "Yayına alıyor, gerçek kullanıcı verisiyle sonraki sürümleri planlıyoruz." },
  ],
  faqTitle: ["Sık sorulan", "sorular."],
  faq: [
    { q: "MVP nedir, neden önce MVP?", a: "MVP, ürünün yalnızca çekirdek özelliklerini içeren ilk sürümüdür. Tüm özellikleri aylarca geliştirmek yerine erken yayına alıp gerçek kullanıcıdan öğrenmenizi sağlar; hem maliyeti hem riski düşürür." },
    { q: "Bir MVP ne kadar sürer?", a: "Kapsama göre 4–8 hafta. Ön değerlendirmede çekirdek özellikleri belirleyip net bir takvim veriyoruz." },
    { q: "Hangi teknolojileri kullanıyorsunuz?", a: "Web tarafında Next.js ve React, mobilde Flutter; veritabanı ve kimlik doğrulama için modern bulut servisleri; ödeme için Stripe gibi altyapılar." },
    { q: "Ödeme ve abonelik sistemi kuruyor musunuz?", a: "Evet. Plan yapısı, deneme süresi, abonelik yönetimi ve faturalandırmayı ürüne entegre ediyoruz." },
    { q: "Teknik bilgim yok, sorun olur mu?", a: "Hayır. Ürün düşüncesini birlikte kuruyor, teknik kararları biz alıyor ve size sade bir dille açıklıyoruz." },
    { q: "MVP sonrası devam ediyor musunuz?", a: "Evet. Yayından sonra kullanıcı verisine göre yeni sürümler geliştirmeye ve ürünü büyütmeye devam ediyoruz." },
  ],
  closingTitle: ["SaaS fikriniz için", "konuşalım."],
  closingLead: "Fikrinizi anlatın; ücretsiz ön değerlendirmede MVP kapsamını, süreyi ve maliyeti birlikte netleştirelim.",
  closingCta: "Bize Ulaşın",
  backLabel: "Ana sayfa",
  serviceType: "SaaS ve MVP geliştirme",
  areaServed: "Türkiye ve yurt dışı",
};

export const saasEN: ServiceContent = {
  locale: "en",
  slug: alternates.en,
  alternates,
  meta: {
    title: "SaaS & MVP Development — From Idea to Product",
    description:
      "SaaS product and MVP development studio. Subscription web apps, user management, payments and scalable architecture — we turn your idea into a testable product fast.",
    keywords: [
      "SaaS development",
      "MVP development",
      "SaaS development agency",
      "startup MVP development",
      "web application development",
      "subscription software development",
      "Next.js SaaS",
    ],
  },
  eyebrow: "SaaS & MVP",
  h1: ["Turn your SaaS idea", "into a real product."],
  lead: "Woodstone Studio is a digital technology studio that builds SaaS products from idea to launch. We start with an MVP containing the core features, then grow it with real user feedback. We build our own SaaS products too — product thinking is second nature to us.",
  ctaPrimary: "Free Assessment",
  ctaSecondary: "See Our Work",
  scopeTitle: ["What we", "do."],
  scopeLead: "A SaaS product is more than an interface; it means subscriptions, users, payments and scale. We build all of it together.",
  scope: [
    { title: "MVP development", desc: "A first version with your idea's most critical features, ready to launch in weeks — to test the market early." },
    { title: "Subscription-based apps", desc: "Plan structure, free trials, subscription management and billing; payment integration with providers like Stripe." },
    { title: "Users, teams & permissions", desc: "Sign-up, login, team/organisation structure, roles and permissions — a solid base for multi-user products." },
    { title: "Dashboards & reporting", desc: "Panels where users run their work, data tables, charts and exports." },
    { title: "APIs & integrations", desc: "Integration with third-party services (payments, email, CRM, AI) and design of your own API." },
    { title: "Scalable architecture", desc: "Next.js, React and modern cloud infrastructure — a technical foundation that doesn't slow you down as you grow." },
  ],
  processTitle: ["How we", "work."],
  process: [
    { step: "01", title: "Assessment", desc: "We clarify the idea, target users and revenue model. Free." },
    { step: "02", title: "MVP scope", desc: "We define the core features of the first release and draw a roadmap." },
    { step: "03", title: "Development", desc: "Weekly deliveries, tested together with you at every step." },
    { step: "04", title: "Launch & growth", desc: "We go live and plan the next releases from real user data." },
  ],
  faqTitle: ["Frequently asked", "questions."],
  faq: [
    { q: "What is an MVP and why start with one?", a: "An MVP is a first version containing only the product's core features. Instead of building everything for months, you launch early and learn from real users — lowering both cost and risk." },
    { q: "How long does an MVP take?", a: "Typically 4–8 weeks depending on scope. We define the core features and a clear timeline at the assessment." },
    { q: "Which technologies do you use?", a: "Next.js and React on the web, Flutter on mobile; modern cloud services for database and auth; providers like Stripe for payments." },
    { q: "Do you set up payments and subscriptions?", a: "Yes. We integrate plan structure, free trials, subscription management and billing into the product." },
    { q: "I have no technical background — is that a problem?", a: "No. We build the product thinking together, make the technical decisions and explain them in plain language." },
    { q: "Do you continue after the MVP?", a: "Yes. After launch we keep developing new releases based on user data and help grow the product." },
  ],
  closingTitle: ["Let's talk about", "your SaaS idea."],
  closingLead: "Tell us your idea; in a free assessment we'll clarify the MVP scope, timeline and cost together.",
  closingCta: "Get in Touch",
  backLabel: "Home",
  serviceType: "SaaS and MVP development",
  areaServed: "Worldwide",
};

export const saasSQ: ServiceContent = {
  locale: "sq",
  slug: alternates.sq,
  alternates,
  meta: {
    title: "Zhvillim SaaS dhe MVP — Nga Ideja te Produkti",
    description:
      "Studio zhvillimi produktesh SaaS dhe MVP për startup-e dhe biznese në Shqipëri dhe Kosovë. Aplikacione web me abonim, menaxhim përdoruesish, pagesa dhe arkitekturë e shkallëzueshme.",
    keywords: [
      "zhvillim SaaS",
      "zhvillim MVP",
      "zhvillim softueri Shqipëri",
      "startup MVP Shqipëri",
      "aplikacion web me abonim",
      "zhvillim produkti dixhital",
      "Next.js SaaS",
    ],
  },
  eyebrow: "SaaS dhe MVP",
  h1: ["Idenë tuaj SaaS", "kthejeni në produkt të vërtetë."],
  lead: "Woodstone Studio është një studio teknologjie dixhitale që ndërton produkte SaaS nga ideja në publikim, për startup-e dhe biznese në Shqipëri, Kosovë dhe më gjerë. Fillojmë me një MVP me veçoritë thelbësore dhe e rrisim me reagimet e përdoruesve realë. Ndërtojmë edhe produktet tona SaaS — mendimin e produktit e njohim nga brenda.",
  ctaPrimary: "Vlerësim Falas",
  ctaSecondary: "Shihni Punët Tona",
  scopeTitle: ["Çfarë", "bëjmë?"],
  scopeLead: "Një produkt SaaS është më shumë se një ndërfaqe; do të thotë abonime, përdorues, pagesa dhe shkallëzim. I ndërtojmë të gjitha së bashku.",
  scope: [
    { title: "Zhvillim MVP", desc: "Një version i parë me veçoritë më kritike të idesë suaj, gati për publikim brenda javësh — për ta testuar tregun herët." },
    { title: "Aplikacione me abonim", desc: "Struktura e planeve, periudha prove, menaxhim abonimesh dhe faturim; integrim pagesash me ofrues si Stripe." },
    { title: "Përdorues, ekipe dhe leje", desc: "Regjistrim, hyrje, strukturë ekipi/organizate, role dhe leje — bazë e fortë për produkte me shumë përdorues." },
    { title: "Panele dhe raportim", desc: "Panele ku përdoruesit menaxhojnë punën, tabela të dhënash, grafikë dhe eksportim." },
    { title: "API dhe integrime", desc: "Integrim me shërbime të palëve të treta (pagesa, email, CRM, AI) dhe dizajn i API-t tuaj." },
    { title: "Arkitekturë e shkallëzueshme", desc: "Next.js, React dhe infrastrukturë moderne cloud — një bazë teknike që nuk ju ngadalëson ndërsa rriteni." },
  ],
  processTitle: ["Si", "punojmë?"],
  process: [
    { step: "01", title: "Vlerësim", desc: "Qartësojmë idenë, përdoruesit e synuar dhe modelin e të ardhurave. Falas." },
    { step: "02", title: "Fushëveprimi i MVP", desc: "Përcaktojmë veçoritë thelbësore të versionit të parë dhe hartojmë një udhërrëfyes." },
    { step: "03", title: "Zhvillim", desc: "Dorëzime javore, të testuara së bashku me ju në çdo hap." },
    { step: "04", title: "Publikim dhe rritje", desc: "Dalim live dhe planifikojmë versionet e ardhshme nga të dhënat reale të përdoruesve." },
  ],
  faqTitle: ["Pyetje të", "bëra shpesh."],
  faq: [
    { q: "Çfarë është MVP dhe pse të fillohet me të?", a: "MVP është versioni i parë që përmban vetëm veçoritë thelbësore të produktit. Në vend që të ndërtoni gjithçka për muaj, publikoni herët dhe mësoni nga përdoruesit realë — duke ulur koston dhe rrezikun." },
    { q: "Sa kohë zgjat një MVP?", a: "Zakonisht 4–8 javë sipas fushëveprimit. Në vlerësim përcaktojmë veçoritë thelbësore dhe një afat të qartë." },
    { q: "Cilat teknologji përdorni?", a: "Next.js dhe React në web, Flutter në mobile; shërbime moderne cloud për bazën e të dhënave dhe autentifikimin; ofrues si Stripe për pagesat." },
    { q: "A e ngrini sistemin e pagesave dhe abonimeve?", a: "Po. Integrojmë strukturën e planeve, periudhën e provës, menaxhimin e abonimeve dhe faturimin në produkt." },
    { q: "Nuk kam njohuri teknike — a është problem?", a: "Jo. Mendimin e produktit e ndërtojmë së bashku, vendimet teknike i marrim ne dhe jua shpjegojmë me gjuhë të thjeshtë." },
    { q: "A vazhdoni pas MVP-së?", a: "Po. Pas publikimit vazhdojmë të zhvillojmë versione të reja bazuar në të dhënat e përdoruesve dhe ndihmojmë në rritjen e produktit." },
  ],
  closingTitle: ["Le të flasim për", "idenë tuaj SaaS."],
  closingLead: "Na tregoni idenë tuaj; në një vlerësim falas qartësojmë së bashku fushëveprimin e MVP-së, afatin dhe koston.",
  closingCta: "Na Kontaktoni",
  backLabel: "Faqja kryesore",
  serviceType: "Zhvillim SaaS dhe MVP",
  areaServed: "Shqipëri, Kosovë",
};
