import type { ServiceContent } from "@/components/service-page";

const alternates = {
  tr: "/saas-gelistirme",
  en: "/en/saas-development",
} as const;

export const saasTR: ServiceContent = {
  locale: "tr",
  slug: alternates.tr,
  alternates,
  meta: {
    title: "SaaS ve MVP Geliştirme — Fikirden Ürüne",
    description:
      "SaaS ürünü ve MVP geliştirme stüdyosu. Abonelik tabanlı web uygulamaları, kullanıcı yönetimi, ödeme altyapısı ve ölçeklenebilir mimari; fikrinizi hızla test edilebilir bir ürüne dönüştürüyoruz.",
    keywords: [
      "SaaS geliştirme",
      "MVP geliştirme",
      "SaaS yazılım geliştirme",
      "startup MVP yaptırmak",
      "web uygulaması geliştirme",
      "abonelik sistemi yazılım",
      "Next.js SaaS",
    ],
  },
  eyebrow: "SaaS ve MVP",
  h1: ["SaaS fikrinizi", "gerçek bir ürüne çevirin."],
  lead: "WoodstoneStudio, SaaS ürünlerini fikirden yayına kadar geliştiren bir dijital teknoloji stüdyosudur. Önce çekirdek özellikleri içeren bir MVP kuruyor, gerçek kullanıcı geri bildirimiyle büyütüyoruz. Kendi SaaS ürünlerimizi de geliştiriyoruz — ürün düşüncesini içeriden biliyoruz.",
  ctaPrimary: "Ücretsiz Ön Değerlendirme",
  ctaSecondary: "Çalışmaları Görün",
  scopeTitle: ["Neler", "yapıyoruz?"],
  scopeLead: "Bir SaaS ürünü sadece arayüz değildir; abonelik, kullanıcı, ödeme ve ölçeklenebilirlik demektir. Hepsini birlikte kuruyoruz.",
  scope: [
    { title: "MVP geliştirme", desc: "Fikrinizin en kritik özelliklerini içeren, haftalar içinde yayına alınabilecek ilk sürüm; pazarı erken test etmek için." },
    { title: "Abonelik tabanlı uygulamalar", desc: "Plan yapısı, deneme süresi, abonelik yönetimi ve faturalandırma; Stripe gibi altyapılarla ödeme entegrasyonu." },
    { title: "Kullanıcı ve yetki yönetimi", desc: "Kayıt, giriş, ekip/organizasyon yapısı, roller ve izinler — çok kullanıcılı ürünler için sağlam temel." },
    { title: "Kontrol paneli ve raporlama", desc: "Kullanıcıların işini yönettiği paneller, veri tabloları, grafikler ve dışa aktarma." },
    { title: "API ve entegrasyonlar", desc: "Üçüncü taraf servislerle (ödeme, e-posta, CRM, AI) entegrasyon ve kendi API'nizin tasarımı." },
    { title: "Ölçeklenebilir mimari", desc: "Next.js, React ve modern bulut altyapısıyla büyüdükçe sizi yavaşlatmayan bir teknik temel." },
  ],
  processTitle: ["Nasıl", "çalışıyoruz?"],
  process: [
    { step: "01", title: "Ön değerlendirme", desc: "Fikri, hedef kullanıcıyı ve gelir modelini netleştiriyoruz. Ücretsiz." },
    { step: "02", title: "MVP kapsamı", desc: "İlk sürüme girecek çekirdek özellikleri belirleyip yol haritası çıkarıyoruz." },
    { step: "03", title: "Geliştirme", desc: "Haftalık teslimatlarla ürünü kuruyor, her adımda sizinle test ediyoruz." },
    { step: "04", title: "Yayın ve büyütme", desc: "Yayına alıyor, gerçek kullanıcı verisiyle sonraki sürümleri planlıyoruz." },
  ],
  faqTitle: ["Sık sorulan", "sorular."],
  faq: [
    { q: "MVP nedir, neden önce MVP?", a: "MVP, ürünün yalnızca çekirdek özelliklerini içeren ilk sürümüdür. Tüm özellikleri aylarca geliştirmek yerine erken yayına alıp gerçek kullanıcıdan öğrenmenizi sağlar; hem maliyeti hem riski düşürür." },
    { q: "Bir MVP ne kadar sürer?", a: "Kapsama göre 4–8 hafta. Ön değerlendirmede çekirdek özellikleri belirleyip net bir takvim veriyoruz." },
    { q: "Hangi teknolojileri kullanıyorsunuz?", a: "Web tarafında Next.js ve React, mobilde Flutter; veritabanı ve kimlik doğrulama için modern bulut servisleri; ödeme için Stripe gibi altyapılar." },
    { q: "Ödeme ve abonelik sistemi kuruyor musunuz?", a: "Evet. Plan yapısı, deneme süresi, abonelik yönetimi ve faturalandırmayı ürüne entegre ediyoruz." },
    { q: "Teknik bilgim yok, sorun olur mu?", a: "Hayır. Ürün düşüncesini birlikte kuruyor, teknik kararları biz alıyor ve size sade bir dille açıklıyoruz." },
    { q: "MVP sonrası devam ediyor musunuz?", a: "Evet. Yayından sonra kullanıcı verisine göre yeni sürümler geliştirmeye ve ürünü büyütmeye devam ediyoruz." },
  ],
  closingTitle: ["SaaS fikriniz için", "konuşalım."],
  closingLead: "Fikrinizi anlatın; ücretsiz ön değerlendirmede MVP kapsamını, süreyi ve maliyeti birlikte netleştirelim.",
  closingCta: "Bize Ulaşın",
  backLabel: "Ana sayfa",
  serviceType: "SaaS ve MVP geliştirme",
  areaServed: "Türkiye ve yurt dışı",
};

export const saasEN: ServiceContent = {
  locale: "en",
  slug: alternates.en,
  alternates,
  meta: {
    title: "SaaS & MVP Development — From Idea to Product",
    description:
      "SaaS product and MVP development studio. Subscription web apps, user management, payments and scalable architecture — we turn your idea into a testable product fast.",
    keywords: [
      "SaaS development",
      "MVP development",
      "SaaS development agency",
      "startup MVP development",
      "web application development",
      "subscription software development",
      "Next.js SaaS",
    ],
  },
  eyebrow: "SaaS & MVP",
  h1: ["Turn your SaaS idea", "into a real product."],
  lead: "WoodstoneStudio is a digital technology studio that builds SaaS products from idea to launch. We start with an MVP containing the core features, then grow it with real user feedback. We build our own SaaS products too — product thinking is second nature to us.",
  ctaPrimary: "Free Assessment",
  ctaSecondary: "See Our Work",
  scopeTitle: ["What we", "do."],
  scopeLead: "A SaaS product is more than an interface; it means subscriptions, users, payments and scale. We build all of it together.",
  scope: [
    { title: "MVP development", desc: "A first version with your idea's most critical features, ready to launch in weeks — to test the market early." },
    { title: "Subscription-based apps", desc: "Plan structure, free trials, subscription management and billing; payment integration with providers like Stripe." },
    { title: "Users, teams & permissions", desc: "Sign-up, login, team/organisation structure, roles and permissions — a solid base for multi-user products." },
    { title: "Dashboards & reporting", desc: "Panels where users run their work, data tables, charts and exports." },
    { title: "APIs & integrations", desc: "Integration with third-party services (payments, email, CRM, AI) and design of your own API." },
    { title: "Scalable architecture", desc: "Next.js, React and modern cloud infrastructure — a technical foundation that doesn't slow you down as you grow." },
  ],
  processTitle: ["How we", "work."],
  process: [
    { step: "01", title: "Assessment", desc: "We clarify the idea, target users and revenue model. Free." },
    { step: "02", title: "MVP scope", desc: "We define the core features of the first release and draw a roadmap." },
    { step: "03", title: "Development", desc: "Weekly deliveries, tested together with you at every step." },
    { step: "04", title: "Launch & growth", desc: "We go live and plan the next releases from real user data." },
  ],
  faqTitle: ["Frequently asked", "questions."],
  faq: [
    { q: "What is an MVP and why start with one?", a: "An MVP is a first version containing only the product's core features. Instead of building everything for months, you launch early and learn from real users — lowering both cost and risk." },
    { q: "How long does an MVP take?", a: "Typically 4–8 weeks depending on scope. We define the core features and a clear timeline at the assessment." },
    { q: "Which technologies do you use?", a: "Next.js and React on the web, Flutter on mobile; modern cloud services for database and auth; providers like Stripe for payments." },
    { q: "Do you set up payments and subscriptions?", a: "Yes. We integrate plan structure, free trials, subscription management and billing into the product." },
    { q: "I have no technical background — is that a problem?", a: "No. We build the product thinking together, make the technical decisions and explain them in plain language." },
    { q: "Do you continue after the MVP?", a: "Yes. After launch we keep developing new releases based on user data and help grow the product." },
  ],
  closingTitle: ["Let's talk about", "your SaaS idea."],
  closingLead: "Tell us your idea; in a free assessment we'll clarify the MVP scope, timeline and cost together.",
  closingCta: "Get in Touch",
  backLabel: "Home",
  serviceType: "SaaS and MVP development",
  areaServed: "Worldwide",
};

