import type { ServiceContent } from "@/components/service-page";

const alternates = {
  tr: "/sosyal-medya",
  en: "/en/social-media",
  sq: "/sq/media-sociale",
} as const;

export const socialTR: ServiceContent = {
  locale: "tr",
  slug: alternates.tr,
  alternates,
  meta: {
    title: "İzmir Sosyal Medya Yönetimi — Instagram ve YouTube",
    description:
      "İzmir merkezli sosyal medya yönetimi: Instagram ve YouTube hesap yönetimi, içerik üretimi (Reels, video), profil düzenleme ve organik büyüme. Kalıcı görünürlük için düzenli, planlı içerik.",
    keywords: [
      "İzmir sosyal medya yönetimi",
      "sosyal medya ajansı İzmir",
      "Instagram hesap yönetimi",
      "YouTube kanal yönetimi",
      "içerik üretimi Reels",
      "organik takipçi büyüme",
      "sosyal medya danışmanlığı",
    ],
  },
  eyebrow: "Sosyal Medya · İzmir",
  h1: ["Sosyal medya yönetimi:", "düzenli içerik, kalıcı görünürlük."],
  lead: "WoodstoneStudio, İzmir merkezli bir dijital teknoloji stüdyosudur. Instagram ve YouTube hesaplarınızı yönetiyor, markanıza uygun içerik üretiyor ve organik büyümeyi destekliyoruz. Odağımız kısa vadeli rakamlar değil; markanızı doğru kitleye ulaştıran, kalıcı bir sosyal medya varlığı.",
  ctaPrimary: "Ücretsiz Profil Değerlendirmesi",
  ctaSecondary: "Çalışmaları Görün",
  scopeTitle: ["Neler", "yapıyoruz?"],
  scopeLead: "Sosyal medya, düzen ister: net bir profil, tutarlı bir dil ve sürekli içerik. Bunları planlıyor, üretiyor ve yönetiyoruz.",
  scope: [
    { title: "Instagram hesap yönetimi", desc: "İçerik takvimi, paylaşım, hikâye, yorum ve mesaj yönetimi — hesabınız her gün canlı ve tutarlı kalır." },
    { title: "YouTube kanal yönetimi", desc: "Kanal düzeni, video başlıkları, açıklamalar, kapak görselleri ve yayın planı; izlenebilir bir kanal yapısı." },
    { title: "İçerik üretimi", desc: "Reels ve kısa videolar, görsel tasarımlar, metinler; markanızın diline uygun, paylaşıma hazır içerik." },
    { title: "Profil düzenleme ve optimizasyon", desc: "Bio, öne çıkanlar, profil görseli, kanal tanıtımı — profiliniz ilk bakışta ne yaptığınızı anlatır." },
    { title: "Organik büyüme", desc: "Doğru hashtag ve konu seçimi, etkileşim yönetimi ve tutarlı yayın ritmiyle gerçek takipçi kazanımı." },
    { title: "Raporlama", desc: "Aylık performans raporu: erişim, etkileşim, takipçi değişimi ve öne çıkan içerikler; birlikte yön belirliyoruz." },
  ],
  processTitle: ["Nasıl", "çalışıyoruz?"],
  process: [
    { step: "01", title: "Profil değerlendirmesi", desc: "Mevcut hesaplarınızı, kitlenizi ve hedefinizi inceliyoruz. Ücretsiz." },
    { step: "02", title: "Strateji ve takvim", desc: "Marka dilini, içerik türlerini ve aylık paylaşım takvimini belirliyoruz." },
    { step: "03", title: "Üretim ve yayın", desc: "İçerikleri üretiyor, onayınızla yayınlıyor ve etkileşimi yönetiyoruz." },
    { step: "04", title: "Ölçüm ve iyileştirme", desc: "Aylık raporla neyin işe yaradığını görüyor, planı buna göre güncelliyoruz." },
  ],
  faqTitle: ["Sık sorulan", "sorular."],
  faq: [
    { q: "Takipçi satın alıyor musunuz?", a: "Hayır. Satın alınan ya da bot takipçi hesabınıza zarar verir ve platform kurallarına aykırıdır. Biz düzenli içerik ve etkileşimle gerçek, organik büyüme sağlıyoruz." },
    { q: "Ne kadar sürede sonuç alınır?", a: "Organik büyüme birikimli çalışır: ilk 4–6 haftada düzen ve etkileşim artışı, 3–6 ayda belirgin takipçi ve erişim büyümesi görülür. Net bir vaat yerine ölçülebilir hedefler koyuyoruz." },
    { q: "İçerikleri kim üretiyor?", a: "Biz üretiyoruz; sizden yalnızca marka bilgisi, ürün/hizmet detayı ve gerektiğinde ham görsel alıyoruz. Her içerik yayınlanmadan önce onayınıza sunulur." },
    { q: "Hangi platformlarda çalışıyorsunuz?", a: "Ağırlıklı olarak Instagram ve YouTube; ihtiyaca göre TikTok ve LinkedIn de yönetiyoruz." },
    { q: "Hesabımın şifresini vermem gerekiyor mu?", a: "Instagram için Meta Business ile yetkili erişim, YouTube için kanal yöneticisi yetkisi yeterlidir; şifre paylaşımı gerekmez." },
    { q: "Fiyatlandırma nasıl?", a: "Platform sayısı, aylık içerik adedi ve yönetim kapsamına göre aylık paket olarak teklif hazırlıyoruz; istediğiniz zaman durdurabilirsiniz." },
  ],
  closingTitle: ["Sosyal medyanız için", "konuşalım."],
  closingLead: "Hesaplarınızı gönderin; ücretsiz profil değerlendirmesinde neyin iyi çalıştığını ve neyi geliştirebileceğimizi paylaşalım.",
  closingCta: "Bize Ulaşın",
  backLabel: "Ana sayfa",
  serviceType: "Sosyal medya yönetimi ve içerik üretimi",
  areaServed: "İzmir, Türkiye",
};

export const socialEN: ServiceContent = {
  locale: "en",
  slug: alternates.en,
  alternates,
  meta: {
    title: "Social Media Management — Instagram & YouTube",
    description:
      "Social media management from İzmir, Turkey: Instagram and YouTube account management, content production (Reels, video), profile optimisation and organic growth. Consistent content for lasting visibility.",
    keywords: [
      "social media management",
      "Instagram account management",
      "YouTube channel management",
      "content production Reels",
      "organic social media growth",
      "social media agency",
      "social media consulting",
    ],
  },
  eyebrow: "Social Media",
  h1: ["Social media management:", "consistent content, lasting visibility."],
  lead: "WoodstoneStudio is a digital technology studio based in İzmir, Turkey. We manage your Instagram and YouTube accounts, produce content in your brand's voice and support organic growth. Our focus is not short-term numbers but a lasting social presence that reaches the right audience.",
  ctaPrimary: "Free Profile Review",
  ctaSecondary: "See Our Work",
  scopeTitle: ["What we", "do."],
  scopeLead: "Social media needs discipline: a clear profile, a consistent voice and continuous content. We plan, produce and manage all three.",
  scope: [
    { title: "Instagram account management", desc: "Content calendar, posting, stories, comment and message handling — your account stays active and consistent every day." },
    { title: "YouTube channel management", desc: "Channel layout, video titles, descriptions, thumbnails and a publishing plan — a channel structure people can follow." },
    { title: "Content production", desc: "Reels and short videos, visual designs and copy, in your brand's voice and ready to publish." },
    { title: "Profile setup & optimisation", desc: "Bio, highlights, profile image, channel trailer — your profile explains what you do at first glance." },
    { title: "Organic growth", desc: "The right hashtags and topics, engagement management and a consistent publishing rhythm to win real followers." },
    { title: "Reporting", desc: "Monthly performance report: reach, engagement, follower change and top content; we set direction together." },
  ],
  processTitle: ["How we", "work."],
  process: [
    { step: "01", title: "Profile review", desc: "We review your current accounts, audience and goals. Free." },
    { step: "02", title: "Strategy & calendar", desc: "We define brand voice, content types and a monthly publishing calendar." },
    { step: "03", title: "Production & publishing", desc: "We produce content, publish it with your approval and manage engagement." },
    { step: "04", title: "Measure & improve", desc: "A monthly report shows what works; we update the plan accordingly." },
  ],
  faqTitle: ["Frequently asked", "questions."],
  faq: [
    { q: "Do you buy followers?", a: "No. Bought or bot followers damage your account and violate platform rules. We deliver real, organic growth through consistent content and engagement." },
    { q: "How quickly do results come?", a: "Organic growth compounds: better structure and engagement in the first 4–6 weeks, noticeable follower and reach growth in 3–6 months. We set measurable goals rather than empty promises." },
    { q: "Who produces the content?", a: "We do; we only need brand information, product/service details and raw visuals where needed. Every piece is submitted for your approval before publishing." },
    { q: "Which platforms do you work on?", a: "Primarily Instagram and YouTube; we also manage TikTok and LinkedIn where needed." },
    { q: "Do I have to share my password?", a: "No. Delegated access via Meta Business for Instagram and channel manager permissions for YouTube are enough." },
    { q: "How is it priced?", a: "A monthly package based on platform count, content volume and management scope; you can pause at any time." },
  ],
  closingTitle: ["Let's talk about", "your social media."],
  closingLead: "Send us your accounts; in a free profile review we'll share what works well and what we can improve.",
  closingCta: "Get in Touch",
  backLabel: "Home",
  serviceType: "Social media management and content production",
  areaServed: "Worldwide",
};

export const socialSQ: ServiceContent = {
  locale: "sq",
  slug: alternates.sq,
  alternates,
  meta: {
    title: "Menaxhim i Mediave Sociale në Shqipëri — Instagram dhe YouTube",
    description:
      "Menaxhim i mediave sociale për biznese në Shqipëri dhe Kosovë: menaxhim llogarish Instagram dhe YouTube, prodhim përmbajtjeje (Reels, video), optimizim profili dhe rritje organike. Përmbajtje e rregullt për dukshmëri të qëndrueshme.",
    keywords: [
      "menaxhim i mediave sociale",
      "menaxhim Instagram Shqipëri",
      "menaxhim kanali YouTube",
      "prodhim përmbajtjeje Reels",
      "rritje organike ndjekësish",
      "agjenci mediash sociale Tiranë",
      "marketing në rrjete sociale",
    ],
  },
  eyebrow: "Media Sociale",
  h1: ["Menaxhim i mediave sociale:", "përmbajtje e rregullt, dukshmëri e qëndrueshme."],
  lead: "WoodstoneStudio është një studio teknologjie dixhitale që punon me biznese në Shqipëri, Kosovë dhe rajon. Menaxhojmë llogaritë tuaja në Instagram dhe YouTube, prodhojmë përmbajtje në zërin e markës suaj dhe mbështesim rritjen organike. Fokusi ynë nuk janë numrat afatshkurtër, por një prani e qëndrueshme që arrin te audienca e duhur.",
  ctaPrimary: "Vlerësim Falas i Profilit",
  ctaSecondary: "Shihni Punët Tona",
  scopeTitle: ["Çfarë", "bëjmë?"],
  scopeLead: "Mediat sociale kërkojnë disiplinë: një profil të qartë, një zë të qëndrueshëm dhe përmbajtje të vazhdueshme. Të tria i planifikojmë, prodhojmë dhe menaxhojmë.",
  scope: [
    { title: "Menaxhim i llogarisë Instagram", desc: "Kalendar përmbajtjeje, postime, story, menaxhim komentesh dhe mesazhesh — llogaria juaj mbetet aktive dhe e qëndrueshme çdo ditë." },
    { title: "Menaxhim i kanalit YouTube", desc: "Strukturë kanali, tituj videosh, përshkrime, thumbnail dhe plan publikimi — një kanal që njerëzit mund ta ndjekin." },
    { title: "Prodhim përmbajtjeje", desc: "Reels dhe video të shkurtra, dizajne vizuale dhe tekste, në zërin e markës suaj dhe gati për publikim." },
    { title: "Rregullim dhe optimizim i profilit", desc: "Bio, highlights, foto profili, trailer i kanalit — profili juaj shpjegon që në shikim të parë çfarë bëni." },
    { title: "Rritje organike", desc: "Hashtag-e dhe tema të duhura, menaxhim i ndërveprimit dhe ritëm i qëndrueshëm publikimi për ndjekës të vërtetë." },
    { title: "Raportim", desc: "Raport mujor performance: shtrirje, ndërveprim, ndryshim ndjekësish dhe përmbajtja më e mirë; drejtimin e vendosim së bashku." },
  ],
  processTitle: ["Si", "punojmë?"],
  process: [
    { step: "01", title: "Vlerësim i profilit", desc: "Shqyrtojmë llogaritë aktuale, audiencën dhe qëllimet tuaja. Falas." },
    { step: "02", title: "Strategji dhe kalendar", desc: "Përcaktojmë zërin e markës, llojet e përmbajtjes dhe kalendarin mujor të publikimit." },
    { step: "03", title: "Prodhim dhe publikim", desc: "Prodhojmë përmbajtjen, e publikojmë me miratimin tuaj dhe menaxhojmë ndërveprimin." },
    { step: "04", title: "Matje dhe përmirësim", desc: "Raporti mujor tregon çfarë funksionon; planin e përditësojmë sipas tij." },
  ],
  faqTitle: ["Pyetje të", "bëra shpesh."],
  faq: [
    { q: "A blini ndjekës?", a: "Jo. Ndjekësit e blerë ose bot-ët e dëmtojnë llogarinë tuaj dhe shkelin rregullat e platformave. Ne sjellim rritje reale dhe organike përmes përmbajtjes së rregullt dhe ndërveprimit." },
    { q: "Sa shpejt vijnë rezultatet?", a: "Rritja organike është kumulative: strukturë dhe ndërveprim më i mirë në 4–6 javët e para, rritje e dukshme e ndjekësve dhe shtrirjes në 3–6 muaj. Vendosim qëllime të matshme, jo premtime boshe." },
    { q: "Kush e prodhon përmbajtjen?", a: "Ne; nga ju na duhen vetëm informacioni i markës, detajet e produktit/shërbimit dhe, kur nevojitet, pamje të papërpunuara. Çdo përmbajtje ju dorëzohet për miratim para publikimit." },
    { q: "Në cilat platforma punoni?", a: "Kryesisht Instagram dhe YouTube; sipas nevojës menaxhojmë edhe TikTok dhe LinkedIn." },
    { q: "A duhet të jap fjalëkalimin?", a: "Jo. Qasja e deleguar përmes Meta Business për Instagram dhe lejet e menaxherit të kanalit për YouTube mjaftojnë." },
    { q: "Si përcaktohet çmimi?", a: "Paketë mujore sipas numrit të platformave, vëllimit të përmbajtjes dhe fushëveprimit të menaxhimit; mund ta ndaloni në çdo kohë." },
  ],
  closingTitle: ["Le të flasim për", "mediat tuaja sociale."],
  closingLead: "Na dërgoni llogaritë tuaja; në një vlerësim falas të profilit ndajmë çfarë funksionon mirë dhe çfarë mund të përmirësojmë.",
  closingCta: "Na Kontaktoni",
  backLabel: "Faqja kryesore",
  serviceType: "Menaxhim i mediave sociale dhe prodhim përmbajtjeje",
  areaServed: "Shqipëri, Kosovë",
};
