import type { ServiceContent } from "@/components/service-page";

const alternates = {
  tr: "/web-tasarim",
  en: "/en/web-design",
  sq: "/sq/dizajn-web",
} as const;

export const webDesignTR: ServiceContent = {
  locale: "tr",
  slug: alternates.tr,
  alternates,
  meta: {
    title: "İzmir Web Tasarım ve Kurumsal Web Sitesi",
    description:
      "İzmir merkezli web tasarım stüdyosu. Kurumsal web siteleri, tanıtım siteleri ve e-ticaret; hızlı, mobil uyumlu ve arama motoru dostu. Ücretsiz ön görüşme.",
    keywords: [
      "İzmir web tasarım",
      "İzmir web tasarım firması",
      "kurumsal web sitesi İzmir",
      "web sitesi yaptırmak",
      "web tasarım ajansı",
      "Next.js web sitesi",
      "mobil uyumlu web sitesi",
    ],
  },
  eyebrow: "Web Tasarım",
  h1: ["İzmir'de web tasarım:", "hızlı, sade, satan siteler."],
  lead: "Woodstone Studio, İzmir merkezli bir dijital teknoloji stüdyosudur. Kurumsal web siteleri, tanıtım siteleri ve e-ticaret arayüzlerini tasarlıyor ve geliştiriyoruz — her biri hız, mobil uyumluluk ve Google'da görünürlük düşünülerek kurulur.",
  ctaPrimary: "Ücretsiz Ön Görüşme",
  ctaSecondary: "Çalışmaları Görün",
  scopeTitle: ["Neler", "yapıyoruz?"],
  scopeLead: "Bir web sitesi sadece güzel görünmez; işinize müşteri getirir. Tasarımı, yazılımı ve arama motoru uyumluluğunu tek elden ele alıyoruz.",
  scope: [
    { title: "Kurumsal web sitesi", desc: "Şirketinizi doğru anlatan, güven veren ve mobilde kusursuz çalışan kurumsal siteler. Hizmet sayfaları, referanslar ve iletişim akışı dahil." },
    { title: "Tanıtım ve landing sayfaları", desc: "Tek bir ürünü, hizmeti ya da kampanyayı anlatan, dönüşüme odaklı sayfalar. Reklam trafiğini müşteriye çevirmek için tasarlanır." },
    { title: "E-ticaret arayüzü", desc: "Ürün listeleme, sepet ve ödeme akışıyla satışa hazır mağaza arayüzleri; hızlı yüklenen, mobilde rahat alışveriş deneyimi." },
    { title: "Yeniden tasarım", desc: "Eski, yavaş ya da mobilde bozulan sitenizi modern altyapıya taşıyoruz. Mevcut içerik ve arama sıralamalarınız korunur." },
    { title: "SEO uyumlu altyapı", desc: "Her site teknik SEO ile teslim edilir: hızlı yükleme, doğru başlık yapısı, yapılandırılmış veri ve arama motorlarının kolay tarayacağı temiz kod." },
    { title: "Bakım ve destek", desc: "Yayından sonra da yanınızdayız; güncellemeler, küçük değişiklikler ve teknik destek için sizinle çalışmaya devam ediyoruz." },
  ],
  processTitle: ["Nasıl", "çalışıyoruz?"],
  process: [
    { step: "01", title: "Ön görüşme", desc: "İşinizi, hedef müşterinizi ve beklentinizi dinliyoruz. Ücretsiz ve yükümlülük yok." },
    { step: "02", title: "Tasarım", desc: "Marka dilinize uygun, sade ve modern bir arayüz tasarlıyor; onayınızla ilerliyoruz." },
    { step: "03", title: "Geliştirme", desc: "Modern teknolojilerle (Next.js, React) hızlı, güvenli ve mobil uyumlu olarak kodluyoruz." },
    { step: "04", title: "Yayın ve destek", desc: "Alan adı, barındırma ve Google kaydını yapıp yayına alıyoruz; sonrasında destek sürüyor." },
  ],
  faqTitle: ["Sık sorulan", "sorular."],
  faq: [
    { q: "Web sitesi yaptırmak ne kadar sürer?", a: "Kapsama göre değişir: bir tanıtım sitesi genellikle 1–2 hafta, çok sayfalı kurumsal bir site 3–5 hafta sürer. Ön görüşmede net bir takvim veriyoruz." },
    { q: "Web tasarım fiyatları nasıl belirleniyor?", a: "Sayfa sayısı, özel işlevler (form, çoklu dil, e-ticaret) ve içerik ihtiyacına göre teklif hazırlıyoruz. Gizli maliyet yoktur; teklif yazılı ve nettir." },
    { q: "Site mobil uyumlu olacak mı?", a: "Evet. Tüm sitelerimiz önce mobil düşünülerek tasarlanır; telefon, tablet ve masaüstünde kusursuz çalışır." },
    { q: "Google'da çıkması için ne yapıyorsunuz?", a: "Teknik SEO standart olarak dahildir: hızlı yükleme, doğru başlık yapısı, yapılandırılmış veri, site haritası ve Google Search Console kurulumu." },
    { q: "İzmir dışından da çalışıyor musunuz?", a: "Evet. İzmir merkezliyiz ancak Türkiye genelinde ve yurt dışında müşterilerle uzaktan çalışıyoruz; site Türkçe, İngilizce ve Arnavutça olarak da hazırlanabilir." },
    { q: "Mevcut sitemi yenileyebilir misiniz?", a: "Evet. Eski ya da yavaş sitenizi modern altyapıya taşırken mevcut içeriğinizi ve arama sıralamalarınızı koruyoruz." },
  ],
  closingTitle: ["Yeni siteniz için", "konuşalım."],
  closingLead: "Fikrinizi ya da mevcut sitenizi bize anlatın; ücretsiz ön görüşmede kapsamı, süreyi ve maliyeti netleştirelim.",
  closingCta: "Bize Ulaşın",
  backLabel: "Ana sayfa",
  serviceType: "Web tasarım ve kurumsal web sitesi geliştirme",
  areaServed: "İzmir, Türkiye",
};

export const webDesignEN: ServiceContent = {
  locale: "en",
  slug: alternates.en,
  alternates,
  meta: {
    title: "Web Design & Corporate Websites",
    description:
      "Web design studio based in İzmir, Turkey, working with clients worldwide. Corporate websites, landing pages and e-commerce — fast, mobile-first and built to rank. Free consultation.",
    keywords: [
      "web design studio",
      "corporate website design",
      "web design Turkey",
      "Next.js website development",
      "landing page design",
      "e-commerce website design",
      "website redesign",
    ],
  },
  eyebrow: "Web Design",
  h1: ["Web design that is fast,", "clean and built to convert."],
  lead: "Woodstone Studio is a digital technology studio based in İzmir, Turkey, working with clients across Europe and beyond. We design and build corporate websites, landing pages and e-commerce storefronts — each one made for speed, mobile use and visibility on Google.",
  ctaPrimary: "Free Consultation",
  ctaSecondary: "See Our Work",
  scopeTitle: ["What we", "do."],
  scopeLead: "A website should do more than look good; it should bring you customers. We handle design, development and search-engine readiness under one roof.",
  scope: [
    { title: "Corporate websites", desc: "Sites that explain your company clearly, build trust and work flawlessly on mobile — with service pages, references and a clear contact flow." },
    { title: "Landing pages", desc: "Conversion-focused pages for a single product, service or campaign, designed to turn ad traffic into enquiries." },
    { title: "E-commerce storefronts", desc: "Product listing, cart and checkout flows that are ready to sell — fast-loading and comfortable to shop on a phone." },
    { title: "Website redesign", desc: "We move outdated, slow or mobile-broken sites onto a modern stack while preserving your content and search rankings." },
    { title: "SEO-ready foundation", desc: "Every site ships with technical SEO: fast loading, correct heading structure, structured data and clean code search engines can crawl easily." },
    { title: "Maintenance & support", desc: "We stay with you after launch — updates, small changes and technical support whenever you need them." },
  ],
  processTitle: ["How we", "work."],
  process: [
    { step: "01", title: "Consultation", desc: "We listen to your business, your customers and your goals. Free, with no obligation." },
    { step: "02", title: "Design", desc: "A clean, modern interface in your brand language — we move forward with your approval at each step." },
    { step: "03", title: "Development", desc: "Built with modern technology (Next.js, React) to be fast, secure and mobile-first." },
    { step: "04", title: "Launch & support", desc: "Domain, hosting and Google registration handled; support continues after go-live." },
  ],
  faqTitle: ["Frequently asked", "questions."],
  faq: [
    { q: "How long does a website take?", a: "It depends on scope: a landing page usually takes 1–2 weeks, a multi-page corporate site 3–5 weeks. We give you a clear timeline at the consultation." },
    { q: "How is web design priced?", a: "We quote based on page count, custom features (forms, multiple languages, e-commerce) and content needs. No hidden costs — the quote is written and clear." },
    { q: "Will the site be mobile-friendly?", a: "Yes. Every site is designed mobile-first and works flawlessly on phones, tablets and desktops." },
    { q: "What do you do for Google visibility?", a: "Technical SEO is included as standard: fast loading, proper heading structure, structured data, a sitemap and Google Search Console setup." },
    { q: "Do you work with clients outside Turkey?", a: "Yes. We are based in İzmir but work remotely with clients across Europe and worldwide; sites can be delivered in English, Turkish and Albanian." },
    { q: "Can you redesign my existing site?", a: "Yes. We move outdated or slow sites onto a modern stack while keeping your existing content and search rankings intact." },
  ],
  closingTitle: ["Let's talk about", "your new site."],
  closingLead: "Tell us about your idea or your current website; in a free consultation we'll clarify scope, timeline and cost.",
  closingCta: "Get in Touch",
  backLabel: "Home",
  serviceType: "Web design and corporate website development",
  areaServed: "Worldwide",
};

export const webDesignSQ: ServiceContent = {
  locale: "sq",
  slug: alternates.sq,
  alternates,
  meta: {
    title: "Dizajn Faqesh Interneti dhe Faqe Korporative në Shqipëri",
    description:
      "Studio dizajni web që punon me klientë në Shqipëri, Tiranë dhe Kosovë. Faqe interneti korporative, landing page dhe e-commerce — të shpejta, të përshtatura për celular dhe të ndërtuara për Google. Konsultë falas.",
    keywords: [
      "dizajn faqe interneti",
      "dizajn web Shqipëri",
      "faqe interneti Tiranë",
      "krijim faqe interneti",
      "faqe interneti korporative",
      "dizajn web Kosovë",
      "faqe interneti me Next.js",
    ],
  },
  eyebrow: "Dizajn Web",
  h1: ["Faqe interneti të shpejta,", "të pastra dhe që sjellin klientë."],
  lead: "Woodstone Studio është një studio teknologjie dixhitale që punon me klientë në Shqipëri, Kosovë dhe rajon. Dizajnojmë dhe ndërtojmë faqe interneti korporative, landing page dhe dyqane online — secila e ndërtuar për shpejtësi, përdorim në celular dhe dukshmëri në Google.",
  ctaPrimary: "Konsultë Falas",
  ctaSecondary: "Shihni Punët Tona",
  scopeTitle: ["Çfarë", "bëjmë?"],
  scopeLead: "Një faqe interneti nuk duhet vetëm të duket bukur; ajo duhet t'ju sjellë klientë. Dizajnin, zhvillimin dhe përgatitjen për motorët e kërkimit i trajtojmë nën një çati.",
  scope: [
    { title: "Faqe interneti korporative", desc: "Faqe që e shpjegojnë qartë kompaninë tuaj, ndërtojnë besim dhe funksionojnë pa gabime në celular — me faqe shërbimesh, referenca dhe rrjedhë të qartë kontakti." },
    { title: "Landing page", desc: "Faqe të përqendruara në konvertim për një produkt, shërbim ose fushatë të vetme, të dizajnuara për ta kthyer trafikun e reklamave në kërkesa." },
    { title: "Dyqane online (e-commerce)", desc: "Listim produktesh, shportë dhe rrjedhë pagese gati për shitje — me ngarkim të shpejtë dhe blerje të lehtë nga telefoni." },
    { title: "Ridizajn i faqes ekzistuese", desc: "Faqen tuaj të vjetër, të ngadaltë ose të prishur në celular e kalojmë në një infrastrukturë moderne, duke ruajtur përmbajtjen dhe renditjen në Google." },
    { title: "Bazë e gatshme për SEO", desc: "Çdo faqe dorëzohet me SEO teknike: ngarkim i shpejtë, strukturë e saktë titujsh, të dhëna të strukturuara dhe kod i pastër që motorët e kërkimit e lexojnë lehtë." },
    { title: "Mirëmbajtje dhe mbështetje", desc: "Qëndrojmë me ju edhe pas publikimit — përditësime, ndryshime të vogla dhe mbështetje teknike sa herë që ju nevojitet." },
  ],
  processTitle: ["Si", "punojmë?"],
  process: [
    { step: "01", title: "Konsultë", desc: "Dëgjojmë biznesin, klientët dhe qëllimet tuaja. Falas dhe pa asnjë detyrim." },
    { step: "02", title: "Dizajn", desc: "Një ndërfaqe e pastër dhe moderne në gjuhën e markës suaj — ecim përpara me miratimin tuaj në çdo hap." },
    { step: "03", title: "Zhvillim", desc: "E ndërtojmë me teknologji moderne (Next.js, React) që të jetë e shpejtë, e sigurt dhe e përshtatur për celular." },
    { step: "04", title: "Publikim dhe mbështetje", desc: "Kujdesemi për domenin, hostimin dhe regjistrimin në Google; mbështetja vazhdon edhe pas publikimit." },
  ],
  faqTitle: ["Pyetje të", "bëra shpesh."],
  faq: [
    { q: "Sa kohë zgjat ndërtimi i një faqeje interneti?", a: "Varet nga fushëveprimi: një landing page zakonisht zgjat 1–2 javë, një faqe korporative me shumë faqe 3–5 javë. Në konsultë ju japim një afat të qartë." },
    { q: "Si përcaktohen çmimet e dizajnit web?", a: "Ofertën e përgatisim sipas numrit të faqeve, funksioneve të veçanta (formularë, shumë gjuhë, e-commerce) dhe nevojave për përmbajtje. Pa kosto të fshehura — oferta është me shkrim dhe e qartë." },
    { q: "A do të jetë faqja e përshtatur për celular?", a: "Po. Të gjitha faqet tona dizajnohen fillimisht për celular dhe funksionojnë pa gabime në telefon, tablet dhe kompjuter." },
    { q: "Çfarë bëni që faqja të dalë në Google?", a: "SEO teknike përfshihet si standard: ngarkim i shpejtë, strukturë e saktë titujsh, të dhëna të strukturuara, hartë e faqes dhe konfigurim i Google Search Console." },
    { q: "A punoni me klientë në Shqipëri dhe Kosovë?", a: "Po. Punojmë nga distanca me klientë në Shqipëri, Kosovë dhe në të gjithë rajonin; faqja mund të dorëzohet në shqip, anglisht dhe turqisht." },
    { q: "A mund ta rinovoni faqen time ekzistuese?", a: "Po. Faqen tuaj të vjetër ose të ngadaltë e kalojmë në një infrastrukturë moderne duke ruajtur përmbajtjen dhe renditjen ekzistuese në kërkim." },
  ],
  closingTitle: ["Le të flasim për", "faqen tuaj të re."],
  closingLead: "Na tregoni idenë tuaj ose faqen aktuale; në një konsultë falas qartësojmë fushëveprimin, afatin dhe koston.",
  closingCta: "Na Kontaktoni",
  backLabel: "Faqja kryesore",
  serviceType: "Dizajn faqesh interneti dhe zhvillim faqesh korporative",
  areaServed: "Shqipëri, Kosovë",
};
